var annotated_dup =
[
    [ "PushData", "structPushData.html", "structPushData" ],
    [ "sbgl_AABB", "structsbgl__AABB.html", "structsbgl__AABB" ],
    [ "sbgl_Camera", "structsbgl__Camera.html", "structsbgl__Camera" ],
    [ "sbgl_Context", "structsbgl__Context.html", "structsbgl__Context" ],
    [ "sbgl_DrawPacket", "structsbgl__DrawPacket.html", "structsbgl__DrawPacket" ],
    [ "sbgl_GfxContext", "structsbgl__GfxContext.html", "structsbgl__GfxContext" ],
    [ "sbgl_GfxTransientAllocation", "structsbgl__GfxTransientAllocation.html", "structsbgl__GfxTransientAllocation" ],
    [ "sbgl_HitResult", "structsbgl__HitResult.html", "structsbgl__HitResult" ],
    [ "sbgl_IndirectCommand", "structsbgl__IndirectCommand.html", "structsbgl__IndirectCommand" ],
    [ "sbgl_InitResult", "structsbgl__InitResult.html", "structsbgl__InitResult" ],
    [ "sbgl_InputState", "structsbgl__InputState.html", "structsbgl__InputState" ],
    [ "sbgl_InstanceData", "structsbgl__InstanceData.html", "structsbgl__InstanceData" ],
    [ "sbgl_InternalContext", "structsbgl__InternalContext.html", "structsbgl__InternalContext" ],
    [ "sbgl_Mat4", "structsbgl__Mat4.html", "structsbgl__Mat4" ],
    [ "sbgl_OrthoParams", "structsbgl__OrthoParams.html", "structsbgl__OrthoParams" ],
    [ "sbgl_PipelineConfig", "structsbgl__PipelineConfig.html", "structsbgl__PipelineConfig" ],
    [ "sbgl_Quat", "unionsbgl__Quat.html", "unionsbgl__Quat" ],
    [ "sbgl_Ray", "structsbgl__Ray.html", "structsbgl__Ray" ],
    [ "sbgl_RenderQueue", "structsbgl__RenderQueue.html", "structsbgl__RenderQueue" ],
    [ "sbgl_Sphere", "structsbgl__Sphere.html", "structsbgl__Sphere" ],
    [ "sbgl_Telemetry", "structsbgl__Telemetry.html", "structsbgl__Telemetry" ],
    [ "sbgl_Vec2", "unionsbgl__Vec2.html", "unionsbgl__Vec2" ],
    [ "sbgl_Vec3", "unionsbgl__Vec3.html", "unionsbgl__Vec3" ],
    [ "sbgl_Vec4", "unionsbgl__Vec4.html", "unionsbgl__Vec4" ],
    [ "sbgl_Vertex", "structsbgl__Vertex.html", "structsbgl__Vertex" ],
    [ "sbgl_VertexAttribute", "structsbgl__VertexAttribute.html", "structsbgl__VertexAttribute" ],
    [ "sbgl_VertexLayout", "structsbgl__VertexLayout.html", "structsbgl__VertexLayout" ],
    [ "SBGL_VulkanBuffer", "structSBGL__VulkanBuffer.html", "structSBGL__VulkanBuffer" ],
    [ "SBGL_VulkanPipeline", "structSBGL__VulkanPipeline.html", "structSBGL__VulkanPipeline" ],
    [ "SBGL_VulkanShader", "structSBGL__VulkanShader.html", "structSBGL__VulkanShader" ],
    [ "sbgl_Window", "structsbgl__Window.html", "structsbgl__Window" ],
    [ "SblArena", "structSblArena.html", "structSblArena" ],
    [ "SblArenaBlock", "structSblArenaBlock.html", "structSblArenaBlock" ],
    [ "SblArenaMark", "structSblArenaMark.html", "structSblArenaMark" ],
    [ "VoxelPushConstants", "structVoxelPushConstants.html", "structVoxelPushConstants" ]
];