var searchData=
[
  ['backed_20allocations_0',['Arena-Backed Allocations',['../md_docs_2manual_2vulkan__backend.html#autotoc_md209',1,'']]],
  ['backend_20architecture_1',['SBgl Vulkan Backend Architecture',['../md_docs_2manual_2vulkan__backend.html',1,'']]],
  ['backend_20multi_20context_20support_2',['Context-Based Backend (Multi-Context Support)',['../md_docs_2manual_2vulkan__backend.html#autotoc_md212',1,'']]],
  ['backend_20refactor_20multi_20context_20support_3',['Context-Based Backend Refactor (Multi-Context Support)',['../md_docs_2ROADMAP.html#autotoc_md229',1,'']]],
  ['based_20backend_20multi_20context_20support_4',['Context-Based Backend (Multi-Context Support)',['../md_docs_2manual_2vulkan__backend.html#autotoc_md212',1,'']]],
  ['based_20backend_20refactor_20multi_20context_20support_5',['Context-Based Backend Refactor (Multi-Context Support)',['../md_docs_2ROADMAP.html#autotoc_md229',1,'']]],
  ['based_20resource_20management_6',['Handle-Based Resource Management',['../md_docs_2manual_2rendering__pipeline.html#autotoc_md152',1,'']]],
  ['basic_20example_20pattern_7',['Basic Example Pattern',['../md_docs_2examples_2index.html#autotoc_md43',1,'']]],
  ['batch_20access_8',['Data-Oriented API (Batch Access)',['../md_docs_2manual_2input__system.html#autotoc_md92',1,'']]],
  ['batch_20collision_9',['Camera System &amp; Batch Collision',['../md_docs_2ROADMAP.html#autotoc_md227',1,'']]],
  ['batch_20collision_20math_10',['Batch Collision Math',['../md_docs_2manual_2camera__system.html#autotoc_md80',1,'']]],
  ['batch_20rendering_20dod_20alignment_11',['Batch Rendering &amp; DOD Alignment',['../md_docs_2manual_2rendering__pipeline.html#autotoc_md169',1,'']]],
  ['batch_20submission_12',['Optimized Batch Submission',['../md_docs_2manual_2rendering__pipeline.html#autotoc_md166',1,'']]],
  ['batch_5fmain_2ec_13',['batch_main.c',['../batch__main_8c.html',1,'']]],
  ['batching_14',['Automated Batching',['../md_docs_2manual_2rendering__pipeline.html#autotoc_md162',1,'']]],
  ['batching_20gpu_20optimization_15',['Batching &amp; GPU Optimization',['../md_docs_2examples_2index.html#autotoc_md41',1,'']]],
  ['batching_20mdi_20bit_20packing_16',['GPU Optimization &amp; Batching (MDI/Bit-packing)',['../md_docs_2ROADMAP.html#autotoc_md231',1,'']]],
  ['bda_17',['Buffer Device Address (BDA)',['../md_docs_2manual_2vulkan__backend.html#autotoc_md217',1,'']]],
  ['bit_20packing_18',['GPU Optimization &amp; Batching (MDI/Bit-packing)',['../md_docs_2ROADMAP.html#autotoc_md231',1,'']]],
  ['block_19',['block',['../structSblArenaMark.html#a29956797d83a5fa702da2c47424f1120',1,'SblArenaMark']]],
  ['block_20layout_20',['Memory Block Layout',['../md_docs_2manual_2memory__management.html#autotoc_md121',1,'']]],
  ['bottleneck_20identification_21',['Bottleneck Identification',['../md_docs_2manual_2telemetry.html#autotoc_md182',1,'']]],
  ['bottom_22',['bottom',['../structsbgl__OrthoParams.html#a25ae9a8fae73548c7569390f0aaa4614',1,'sbgl_OrthoParams']]],
  ['boundpipeline_23',['boundPipeline',['../structsbgl__GfxContext.html#ad3439cabe68f47a670cfae9d9942b29b',1,'sbgl_GfxContext']]],
  ['brace_20initialization_24',['Technical Detail (Brace Initialization)',['../md_docs_2manual_2math__library.html#autotoc_md111',1,'']]],
  ['buffer_25',['buffer',['../structsbgl__GfxTransientAllocation.html#a83bb0f558818a483f04b6226b1d4b9f7',1,'sbgl_GfxTransientAllocation::buffer'],['../md_docs_2getting__started_2first__triangle.html#autotoc_md50',1,'Vertex Buffer']]],
  ['buffer_20device_20address_20bda_26',['Buffer Device Address (BDA)',['../md_docs_2manual_2vulkan__backend.html#autotoc_md217',1,'']]],
  ['buffer_20sub_20allocation_27',['Ring-Buffer Sub-allocation',['../md_docs_2manual_2memory__management.html#autotoc_md128',1,'']]],
  ['buffering_203d_20sorting_28',['Depth Buffering &amp; 3D Sorting',['../md_docs_2manual_2rendering__pipeline.html#autotoc_md160',1,'']]],
  ['buffers_29',['buffers',['../structsbgl__GfxContext.html#ad9edb2c408a025f3fc4b4417ced56c20',1,'sbgl_GfxContext::buffers'],['../md_docs_2manual_2memory__management.html#autotoc_md127',1,'Transient GPU Buffers']]],
  ['buffers_20triangle_20rendering_30',['Vertex Buffers &amp; Triangle Rendering',['../md_docs_2ROADMAP.html#autotoc_md228',1,'']]],
  ['build_20instructions_31',['build instructions',['../md_docs_2getting__started_2installation.html#autotoc_md60',1,'Build Instructions'],['../md_docs_2getting__started_2installation.html#autotoc_md64',1,'Build Instructions'],['../md_docs_2getting__started_2installation.html#autotoc_md68',1,'Build Instructions']]],
  ['building_20the_20examples_32',['Building the Examples',['../md_docs_2examples_2index.html#autotoc_md36',1,'']]]
];
