var searchData=
[
  ['radius_0',['radius',['../structsbgl__Sphere.html#a582c8774833017e88d01cdf475624b87',1,'sbgl_Sphere']]],
  ['range_20tracking_1',['Managed Heap Range Tracking',['../md_docs_2manual_2vulkan__backend.html#managed-heap-range-tracking',1,'']]],
  ['rangecount_2',['rangeCount',['../structsbgl__GfxManagedHeap.html#a59bc939cc168017e0d33d94aa95601bb',1,'sbgl_GfxManagedHeap']]],
  ['ranges_3',['ranges',['../structsbgl__GfxManagedHeap.html#aed777d5c6e51a06adca7c1f177835ab0',1,'sbgl_GfxManagedHeap']]],
  ['raw_20input_4',['Cursor Locking and Raw Input',['../md_docs_2manual_2windows__specific.html#cursor-locking-and-raw-input',1,'']]],
  ['raw_20input_20implementation_5',['Raw Input Implementation',['../md_docs_2manual_2windows__specific.html#raw-input-implementation',1,'']]],
  ['reading_6',['Reading',['../md_docs_2manual_2platform__abstraction.html#references--further-reading',1,'References &amp; Further Reading'],['../md_docs_2manual_2vulkan__backend.html#references--further-reading-1',1,'References &amp; Further Reading']]],
  ['readme_2emd_7',['README.md',['../README_8md.html',1,'']]],
  ['ready_8',['Core Matrix &amp; Math (simd-ready)',['../md_docs_2ROADMAP.html#core-matrix--math-simd-ready',1,'']]],
  ['recommendation_9',['Recommendation',['../md_docs_2manual_2windows__specific.html#recommendation',1,'']]],
  ['recommended_10',['Using MSYS2 (Recommended)',['../md_docs_2getting__started_2installation.html#using-msys2-recommended',1,'']]],
  ['recording_11',['Parallel Command Recording',['../md_docs_2ROADMAP.html#parallel-command-recording',1,'']]],
  ['recreate_5fswapchain_12',['recreate_swapchain',['../sbgl__backend__vulkan_8c.html#a51a35fd284d60e3d4c453766ebdd640a',1,'sbgl_backend_vulkan.c']]],
  ['recreation_20mark_20rewind_13',['Dynamic Swapchain Recreation (Mark/Rewind)',['../md_docs_2manual_2vulkan__backend.html#dynamic-swapchain-recreation-markrewind',1,'']]],
  ['refactor_20multi_20context_20support_14',['Context-Based Backend Refactor (Multi-Context Support)',['../md_docs_2ROADMAP.html#context-based-backend-refactor-multi-context-support',1,'']]],
  ['references_20further_20reading_15',['References Further Reading',['../md_docs_2manual_2platform__abstraction.html#references--further-reading',1,'References &amp; Further Reading'],['../md_docs_2manual_2vulkan__backend.html#references--further-reading-1',1,'References &amp; Further Reading']]],
  ['registration_16',['Window Class Registration',['../md_docs_2manual_2windows__specific.html#window-class-registration',1,'']]],
  ['registry_5fhandle_5fglobal_17',['registry_handle_global',['../window__wayland_8c.html#af288e02a94c196a68b327fc55c049932',1,'window_wayland.c']]],
  ['registry_5flistener_18',['registry_listener',['../window__wayland_8c.html#a8998c87c94cd7d185e8f0cdafab4b1c4',1,'window_wayland.c']]],
  ['relationship_20with_20tt_20sbgl_5fcontext_20tt_19',['Relationship with &lt;tt&gt;sbgl_Context&lt;/tt&gt;',['../md_docs_2manual_2platform__abstraction.html#relationship-with-sbgl_context',1,'']]],
  ['relative_5fmotion_20',['relative_motion',['../input__wayland_8c.html#a3320d290c100178c10677c49c07e00c6',1,'input_wayland.c']]],
  ['relative_5fpointer_5flistener_21',['relative_pointer_listener',['../input__wayland_8c.html#a4f77c6bb33fb6dc5c92228e95b268d87',1,'relative_pointer_listener:&#160;input_wayland.c'],['../window__wayland_8c.html#a4f77c6bb33fb6dc5c92228e95b268d87',1,'relative_pointer_listener:&#160;input_wayland.c']]],
  ['render_20distance_20control_22',['Render Distance Control',['../md_docs_2manual_2voxel__rendering.html#render-distance-control',1,'']]],
  ['render_20queues_23',['Render Queues',['../md_docs_2manual_2rendering__pipeline.html#render-queues',1,'']]],
  ['renderfinishedsemaphores_24',['renderFinishedSemaphores',['../structsbgl__GfxContext.html#a5a7a020732a50cd3d2c63db2acd32919',1,'sbgl_GfxContext']]],
  ['rendering_25',['Vertex Buffers &amp; Triangle Rendering',['../md_docs_2ROADMAP.html#vertex-buffers--triangle-rendering',1,'']]],
  ['rendering_20architecture_26',['Voxel Rendering Architecture',['../md_docs_2manual_2voxel__rendering.html',1,'']]],
  ['rendering_20dod_20alignment_27',['Batch Rendering &amp; DOD Alignment',['../md_docs_2manual_2rendering__pipeline.html#batch-rendering--dod-alignment',1,'']]],
  ['rendering_20guide_28',['Triangle Rendering Guide',['../md_docs_2getting__started_2first__triangle.html',1,'']]],
  ['rendering_20pipeline_29',['SBgl Rendering Pipeline',['../md_docs_2manual_2rendering__pipeline.html',1,'']]],
  ['rendering_20techniques_30',['Performance &amp; Rendering Techniques',['../md_README.html#performance--rendering-techniques',1,'']]],
  ['rendering_20text_20sprites_31',['High-Level rendering (Text/Sprites)',['../md_docs_2ROADMAP.html#high-level-rendering-textsprites',1,'']]],
  ['rendering_5fpipeline_2emd_32',['rendering_pipeline.md',['../rendering__pipeline_8md.html',1,'']]],
  ['renderpushconstants_33',['RenderPushConstants',['../structRenderPushConstants.html',1,'']]],
  ['repeat_20behavior_34',['Key Repeat Behavior',['../md_docs_2manual_2windows__specific.html#key-repeat-behavior',1,'']]],
  ['reported_35',['When Errors Are Reported',['../md_docs_2manual_2windows__specific.html#when-errors-are-reported',1,'']]],
  ['reporting_36',['Error Reporting',['../md_docs_2manual_2windows__specific.html#error-reporting',1,'']]],
  ['requirements_37',['Memory &amp; Synchronization Requirements',['../md_docs_2manual_2voxel__rendering.html#memory--synchronization-requirements',1,'']]],
  ['resized_38',['resized',['../structsbgl__Window.html#a8b710d1cfbc87eec5e9c7aaf822313d6',1,'sbgl_Window']]],
  ['resource_20cleanup_39',['Resource Cleanup',['../md_docs_2getting__started_2first__triangle.html#resource-cleanup',1,'']]],
  ['resource_20limits_40',['Resource Limits',['../md_docs_2manual_2rendering__pipeline.html#configurable-resource-limits',1,'Configurable Resource Limits'],['../md_docs_2manual_2vulkan__backend.html#configurable-resource-limits-1',1,'Configurable Resource Limits'],['../md_README.html#custom-resource-limits',1,'Custom Resource Limits'],['../md_docs_2getting__started_2window__setup.html#default-resource-limits',1,'Default Resource Limits']]],
  ['resource_20management_41',['Handle-Based Resource Management',['../md_docs_2manual_2rendering__pipeline.html#handle-based-resource-management',1,'']]],
  ['resource_20management_20mark_20rewind_42',['Dynamic Resource Management (Mark/Rewind)',['../md_docs_2manual_2memory__management.html#dynamic-resource-management-markrewind',1,'']]],
  ['resources_43',['Additional Resources',['../md_docs_2manual_2windows__specific.html#additional-resources',1,'']]],
  ['responsibility_44',['User Responsibility',['../md_docs_2manual_2platform__abstraction.html#user-responsibility',1,'']]],
  ['result_45',['Result',['../md_docs_2manual_2windows__specific.html#result',1,'']]],
  ['result_46',['result',['../structsbgl__Context.html#abe268ff7fded4efc67005acc9b7f42f0',1,'sbgl_Context::result'],['../structsbgl__GfxContext.html#a400dbabc71ebc443318cce30708168fb',1,'sbgl_GfxContext::result']]],
  ['rewind_47',['Rewind',['../md_docs_2manual_2memory__management.html#dynamic-resource-management-markrewind',1,'Dynamic Resource Management (Mark/Rewind)'],['../md_docs_2manual_2vulkan__backend.html#dynamic-swapchain-recreation-markrewind',1,'Dynamic Swapchain Recreation (Mark/Rewind)']]],
  ['right_48',['right',['../structsbgl__OrthoParams.html#a5c71980612815f42aecfb675f0a8558e',1,'sbgl_OrthoParams']]],
  ['roadmap_49',['SBgl Roadmap',['../md_docs_2ROADMAP.html',1,'']]],
  ['roadmap_2emd_50',['ROADMAP.md',['../ROADMAP_8md.html',1,'']]],
  ['root_51',['Inverse Square Root',['../md_docs_2manual_2math__library.html#inverse-square-root',1,'']]],
  ['rotate_5flogs_52',['rotate_logs',['../sbgl__log_8c.html#a9249823bd3120016c23778b634d8c818',1,'sbgl_log.c']]],
  ['rotation_20with_20quaternions_53',['Rotation with Quaternions',['../md_docs_2manual_2math__library.html#rotation-with-quaternions',1,'']]],
  ['roughness_54',['roughness',['../structsbgl__Material.html#a49e269806413183b65928db9a5cd46ab',1,'sbgl_Material']]],
  ['running_20an_20example_55',['Running an Example',['../md_docs_2examples_2index.html#running-an-example',1,'']]]
];
