var searchData=
[
  ['abstraction_20layer_20hal_0',['SBgl Platform Abstraction Layer (HAL)',['../md_docs_2manual_2platform__abstraction.html',1,'']]],
  ['access_1',['Data-Oriented API (Batch Access)',['../md_docs_2manual_2input__system.html#autotoc_md98',1,'']]],
  ['active_2',['active',['../structSBGL__VulkanBuffer.html#ad8cb1d843e59a2f051d3018dc6dd55cd',1,'SBGL_VulkanBuffer::active'],['../structSBGL__VulkanShader.html#aea2b6318abaed5b222f344889b2db2a3',1,'SBGL_VulkanShader::active'],['../structSBGL__VulkanPipeline.html#a5d73a7f029161d731b8de7b7b23d5579',1,'SBGL_VulkanPipeline::active']]],
  ['added_3',['Added',['../md_CHANGELOG.html#autotoc_md22',1,'Added'],['../md_CHANGELOG.html#autotoc_md26',1,'Added'],['../md_CHANGELOG.html#autotoc_md29',1,'Added'],['../md_CHANGELOG.html#autotoc_md33',1,'Added'],['../md_CHANGELOG.html#autotoc_md35',1,'Added']]],
  ['address_20bda_4',['Buffer Device Address (BDA)',['../md_docs_2manual_2vulkan__backend.html#autotoc_md224',1,'']]],
  ['advanced_20techniques_5',['Chapter 4: Advanced Techniques',['../index.html#autotoc_md4',1,'']]],
  ['advanced_3a_20interactive_20shaders_6',['Advanced: Interactive Shaders',['../md_docs_2examples_2index.html#autotoc_md49',1,'']]],
  ['alignment_7',['Batch Rendering &amp; DOD Alignment',['../md_docs_2manual_2rendering__pipeline.html#autotoc_md176',1,'']]],
  ['allocation_8',['Ring-Buffer Sub-allocation',['../md_docs_2manual_2memory__management.html#autotoc_md135',1,'']]],
  ['allocations_9',['Arena-Backed Allocations',['../md_docs_2manual_2vulkan__backend.html#autotoc_md216',1,'']]],
  ['allocator_20sblarena_10',['The Arena Allocator (SblArena)',['../md_docs_2manual_2memory__management.html#autotoc_md129',1,'']]],
  ['an_20example_11',['Running an Example',['../md_docs_2examples_2index.html#autotoc_md41',1,'']]],
  ['and_20closure_12',['Window Lifecycle and Closure',['../md_docs_2manual_2platform__abstraction.html#autotoc_md148',1,'']]],
  ['and_20design_13',['Architecture and Design',['../md_docs_2manual_2math__library.html#autotoc_md107',1,'']]],
  ['and_20ownership_14',['Core Hierarchy and Ownership',['../md_docs_2manual_2memory__management.html#autotoc_md126',1,'']]],
  ['and_20queue_20management_15',['Logical Device and Queue Management',['../md_docs_2manual_2vulkan__backend.html#autotoc_md207',1,'']]],
  ['api_20batch_20access_16',['Data-Oriented API (Batch Access)',['../md_docs_2manual_2input__system.html#autotoc_md98',1,'']]],
  ['api_20standardization_20error_20handling_17',['API Standardization &amp; Error Handling',['../md_docs_2ROADMAP.html#autotoc_md238',1,'']]],
  ['application_20integration_18',['Application Integration',['../md_docs_2manual_2input__system.html#autotoc_md97',1,'']]],
  ['apply_5fradius_5fchange_19',['apply_radius_change',['../voxel__main_8c.html#a337fcbf862cb95d02e717c47a74cd869',1,'voxel_main.c']]],
  ['architecture_20',['Architecture',['../md_docs_2manual_2telemetry.html#autotoc_md182',1,'Architecture'],['../md_docs_2manual_2memory__management.html#autotoc_md130',1,'Block Header Architecture'],['../md_docs_2manual_2camera__system.html#autotoc_md81',1,'Camera Architecture'],['../md_docs_2manual_2math__library.html',1,'Math Library Architecture'],['../md_docs_2manual_2memory__management.html',1,'Memory Management Architecture'],['../md_docs_2manual_2input__system.html',1,'SBgl Input System Architecture'],['../md_docs_2manual_2vulkan__backend.html',1,'SBgl Vulkan Backend Architecture'],['../md_docs_2manual_2voxel__rendering.html',1,'Voxel Rendering Architecture']]],
  ['architecture_20and_20design_21',['Architecture and Design',['../md_docs_2manual_2math__library.html#autotoc_md107',1,'']]],
  ['arena_22',['The Transient Arena',['../md_docs_2manual_2memory__management.html#autotoc_md132',1,'']]],
  ['arena_23',['arena',['../structsbgl__GfxContext.html#a4996512a8fd993d5cc776f1acd23b0b4',1,'sbgl_GfxContext::arena'],['../structsbgl__RenderQueue.html#af0d8742271c05ef716c5a5291bbd1215',1,'sbgl_RenderQueue::arena'],['../structsbgl__InternalContext.html#ad850e4314963cbecbf1913882ccaedef',1,'sbgl_InternalContext::arena']]],
  ['arena_20allocator_20sblarena_24',['The Arena Allocator (SblArena)',['../md_docs_2manual_2memory__management.html#autotoc_md129',1,'']]],
  ['arena_20backed_20allocations_25',['Arena-Backed Allocations',['../md_docs_2manual_2vulkan__backend.html#autotoc_md216',1,'']]],
  ['arena_20hierarchy_20ascii_26',['Arena Hierarchy (ASCII)',['../md_docs_2manual_2memory__management.html#autotoc_md133',1,'']]],
  ['ascii_27',['ASCII',['../md_docs_2manual_2memory__management.html#autotoc_md133',1,'Arena Hierarchy (ASCII)'],['../md_docs_2manual_2memory__management.html#autotoc_md136',1,'CPU-GPU Interaction (ASCII)']]],
  ['aspect_28',['aspect',['../structsbgl__Camera.html#a95d90d29f1d5d591bbab7777420e431d',1,'sbgl_Camera']]],
  ['attributecount_29',['attributeCount',['../structsbgl__VertexLayout.html#add8e0b16c2179a83b93a104d78fea448',1,'sbgl_VertexLayout']]],
  ['attributes_30',['attributes',['../structsbgl__VertexLayout.html#aa69ed279d85326a353914f2bd19f7d37',1,'sbgl_VertexLayout']]],
  ['automated_20batching_31',['Automated Batching',['../md_docs_2manual_2rendering__pipeline.html#autotoc_md169',1,'']]]
];
