var searchData=
[
  ['backend_20architecture_0',['SBgl Vulkan Backend Architecture',['../md_docs_2manual_2vulkan__backend.html',1,'']]],
  ['backend_20multi_20context_20support_1',['Context-Based Backend (Multi-Context Support)',['../md_docs_2manual_2vulkan__backend.html#autotoc_md234',1,'']]],
  ['backend_20refactor_20multi_20context_20support_2',['Context-Based Backend Refactor (Multi-Context Support)',['../md_docs_2ROADMAP.html#autotoc_md252',1,'']]],
  ['based_20backend_20multi_20context_20support_3',['Context-Based Backend (Multi-Context Support)',['../md_docs_2manual_2vulkan__backend.html#autotoc_md234',1,'']]],
  ['based_20backend_20refactor_20multi_20context_20support_4',['Context-Based Backend Refactor (Multi-Context Support)',['../md_docs_2ROADMAP.html#autotoc_md252',1,'']]],
  ['based_20resource_20management_5',['Handle-Based Resource Management',['../md_docs_2manual_2rendering__pipeline.html#autotoc_md173',1,'']]],
  ['basic_20example_20pattern_6',['Basic Example Pattern',['../md_docs_2examples_2index.html#autotoc_md60',1,'']]],
  ['basic_20use_20case_20pattern_7',['Basic use case Pattern',['../md_README.html#autotoc_md9',1,'']]],
  ['batch_20access_8',['Data-Oriented API (Batch Access)',['../md_docs_2manual_2input__system.html#autotoc_md111',1,'']]],
  ['batch_20collision_9',['Camera System &amp; Batch Collision',['../md_docs_2ROADMAP.html#autotoc_md250',1,'']]],
  ['batch_20collision_20math_10',['Batch Collision Math',['../md_docs_2manual_2camera__system.html#autotoc_md99',1,'']]],
  ['batch_20rendering_20dod_20alignment_11',['Batch Rendering &amp; DOD Alignment',['../md_docs_2manual_2rendering__pipeline.html#autotoc_md190',1,'']]],
  ['batch_20submission_12',['Optimized Batch Submission',['../md_docs_2manual_2rendering__pipeline.html#autotoc_md187',1,'']]],
  ['batch_5fmain_2ec_13',['batch_main.c',['../batch__main_8c.html',1,'']]],
  ['batching_14',['Automated Batching',['../md_docs_2manual_2rendering__pipeline.html#autotoc_md183',1,'']]],
  ['batching_20gpu_20optimization_15',['Batching &amp; GPU Optimization',['../md_docs_2examples_2index.html#autotoc_md58',1,'']]],
  ['batching_20mdi_20bit_20packing_16',['GPU Optimization &amp; Batching (MDI/Bit-packing)',['../md_docs_2ROADMAP.html#autotoc_md254',1,'']]],
  ['bda_17',['Buffer Device Address (BDA)',['../md_docs_2manual_2vulkan__backend.html#autotoc_md239',1,'']]],
  ['benefits_18',['Data-Oriented Design (DOD) Benefits',['../md_docs_2manual_2memory__management.html#autotoc_md149',1,'']]],
  ['between_20compute_20and_20graphics_20shaders_19',['Differences Between Compute and Graphics Shaders',['../md_docs_2COMPUTE.html#autotoc_md43',1,'']]],
  ['bit_20packing_20',['GPU Optimization &amp; Batching (MDI/Bit-packing)',['../md_docs_2ROADMAP.html#autotoc_md254',1,'']]],
  ['block_21',['block',['../structSblArenaMark.html#a29956797d83a5fa702da2c47424f1120',1,'SblArenaMark']]],
  ['block_20header_20architecture_22',['Block Header Architecture',['../md_docs_2manual_2memory__management.html#autotoc_md143',1,'']]],
  ['block_20layout_23',['Memory Block Layout',['../md_docs_2manual_2memory__management.html#autotoc_md140',1,'']]],
  ['bottleneck_20identification_24',['Bottleneck Identification',['../md_docs_2manual_2telemetry.html#autotoc_md203',1,'']]],
  ['bottom_25',['bottom',['../structsbgl__OrthoParams.html#a25ae9a8fae73548c7569390f0aaa4614',1,'sbgl_OrthoParams']]],
  ['boundcomputepipeline_26',['boundComputePipeline',['../structsbgl__GfxContext.html#aeca44381965753f5db4403ba1b57fd54',1,'sbgl_GfxContext']]],
  ['boundpipeline_27',['boundPipeline',['../structsbgl__GfxContext.html#ad3439cabe68f47a670cfae9d9942b29b',1,'sbgl_GfxContext']]],
  ['brace_20initialization_28',['Technical Detail (Brace Initialization)',['../md_docs_2manual_2math__library.html#autotoc_md130',1,'']]],
  ['buffer_29',['Vertex Buffer',['../md_docs_2getting__started_2first__triangle.html#autotoc_md67',1,'']]],
  ['buffer_30',['buffer',['../structsbgl__GfxTransientAllocation.html#a83bb0f558818a483f04b6226b1d4b9f7',1,'sbgl_GfxTransientAllocation']]],
  ['buffer_20device_20address_20bda_31',['Buffer Device Address (BDA)',['../md_docs_2manual_2vulkan__backend.html#autotoc_md239',1,'']]],
  ['bufferactive_32',['bufferActive',['../structsbgl__GfxContext.html#a012bff549bc07385987c68481642f58a',1,'sbgl_GfxContext']]],
  ['buffering_203d_20sorting_33',['Depth Buffering &amp; 3D Sorting',['../md_docs_2manual_2rendering__pipeline.html#autotoc_md181',1,'']]],
  ['buffers_34',['buffers',['../structsbgl__GfxContext.html#ad9edb2c408a025f3fc4b4417ced56c20',1,'sbgl_GfxContext']]],
  ['buffers_20triangle_20rendering_35',['Vertex Buffers &amp; Triangle Rendering',['../md_docs_2ROADMAP.html#autotoc_md251',1,'']]],
  ['build_20instructions_36',['Build Instructions',['../md_docs_2getting__started_2installation.html#autotoc_md79',1,'Build Instructions'],['../md_docs_2getting__started_2installation.html#autotoc_md83',1,'Build Instructions'],['../md_docs_2getting__started_2installation.html#autotoc_md87',1,'Build Instructions']]],
  ['building_20the_20examples_37',['Building the Examples',['../md_docs_2examples_2index.html#autotoc_md53',1,'']]]
];
