var searchData=
[
  ['a_20compute_20pipeline_0',['Creating a Compute Pipeline',['../md_docs_2COMPUTE.html#creating-a-compute-pipeline',1,'']]],
  ['aabbaddress_1',['aabbAddress',['../structsbgl__CullPushConstants.html#a45e444bb78b316fc439a0041e2d76e7a',1,'sbgl_CullPushConstants::aabbAddress'],['../structRenderPushConstants.html#a1b7992a58db4bcd80b3cce727c162994',1,'RenderPushConstants::aabbAddress']]],
  ['aabbbuf_2',['aabbBuf',['../structsbgl__VoxelSystem.html#a7aac72da414377288c88873ee2b7c293',1,'sbgl_VoxelSystem']]],
  ['abstraction_20layer_20hal_3',['SBgl Platform Abstraction Layer (HAL)',['../md_docs_2manual_2platform__abstraction.html',1,'']]],
  ['access_4',['Data-Oriented API (Batch Access)',['../md_docs_2manual_2input__system.html#data-oriented-api-batch-access',1,'']]],
  ['accumulateddeltax_5',['accumulatedDeltaX',['../structsbgl__Window.html#ad76046c38b30e66bd1bdb8d60119b85a',1,'sbgl_Window']]],
  ['accumulateddeltay_6',['accumulatedDeltaY',['../structsbgl__Window.html#a75c96fdc18411c1c728375c1be7cb7a3',1,'sbgl_Window']]],
  ['active_7',['active',['../structSBGL__VulkanShader.html#aea2b6318abaed5b222f344889b2db2a3',1,'SBGL_VulkanShader::active'],['../structSBGL__VulkanPipeline.html#a5d73a7f029161d731b8de7b7b23d5579',1,'SBGL_VulkanPipeline::active'],['../structSBGL__VulkanComputePipeline.html#a61091f80394764371eb8d2fd54b81e6c',1,'SBGL_VulkanComputePipeline::active'],['../structVoxelPool.html#a4efc2c0345f5668d187a9cd85c5c7cdc',1,'VoxelPool::active']]],
  ['added_8',['Added',['../md_CHANGELOG.html#added',1,'Added'],['../md_CHANGELOG.html#added-1',1,'Added'],['../md_CHANGELOG.html#added-2',1,'Added'],['../md_CHANGELOG.html#added-3',1,'Added'],['../md_CHANGELOG.html#added-4',1,'Added'],['../md_CHANGELOG.html#added-5',1,'Added'],['../md_CHANGELOG.html#added-6',1,'Added'],['../md_CHANGELOG.html#added-7',1,'Added']]],
  ['additional_20resources_9',['Additional Resources',['../md_docs_2manual_2windows__specific.html#additional-resources',1,'']]],
  ['address_20bda_10',['Buffer Device Address (BDA)',['../md_docs_2manual_2vulkan__backend.html#buffer-device-address-bda',1,'']]],
  ['advanced_20techniques_11',['Chapter 4: Advanced Techniques',['../index.html#chapter-4-advanced-techniques',1,'']]],
  ['advanced_3a_20interactive_20shaders_12',['Advanced: Interactive Shaders',['../md_docs_2examples_2index.html#advanced-interactive-shaders',1,'']]],
  ['alignment_13',['Batch Rendering &amp; DOD Alignment',['../md_docs_2manual_2rendering__pipeline.html#batch-rendering--dod-alignment',1,'']]],
  ['allocation_20strategies_14',['Allocation Strategies',['../md_docs_2manual_2memory__management.html#allocation-strategies',1,'']]],
  ['allocator_20sblarena_15',['The Arena Allocator (SblArena)',['../md_docs_2manual_2memory__management.html#the-arena-allocator-sblarena',1,'']]],
  ['an_20example_16',['Running an Example',['../md_docs_2examples_2index.html#running-an-example',1,'']]],
  ['and_20behaviors_17',['Windows-Specific Features and Behaviors',['../md_docs_2manual_2windows__specific.html',1,'']]],
  ['and_20closure_18',['Window Lifecycle and Closure',['../md_docs_2manual_2platform__abstraction.html#window-lifecycle-and-closure',1,'']]],
  ['and_20design_19',['Architecture and Design',['../md_docs_2manual_2math__library.html#architecture-and-design',1,'']]],
  ['and_20graphics_20shaders_20',['Differences Between Compute and Graphics Shaders',['../md_docs_2COMPUTE.html#differences-between-compute-and-graphics-shaders',1,'']]],
  ['and_20ownership_21',['Core Hierarchy and Ownership',['../md_docs_2manual_2memory__management.html#core-hierarchy-and-ownership',1,'']]],
  ['and_20queue_20management_22',['Logical Device and Queue Management',['../md_docs_2manual_2vulkan__backend.html#logical-device-and-queue-management',1,'']]],
  ['and_20raw_20input_23',['Cursor Locking and Raw Input',['../md_docs_2manual_2windows__specific.html#cursor-locking-and-raw-input',1,'']]],
  ['api_24',['Using the Compute API',['../md_docs_2COMPUTE.html#using-the-compute-api',1,'']]],
  ['api_20batch_20access_25',['Data-Oriented API (Batch Access)',['../md_docs_2manual_2input__system.html#data-oriented-api-batch-access',1,'']]],
  ['api_20standardization_20error_20handling_26',['API Standardization &amp; Error Handling',['../md_docs_2ROADMAP.html#api-standardization--error-handling',1,'']]],
  ['application_20integration_27',['Application Integration',['../md_docs_2manual_2input__system.html#application-integration',1,'']]],
  ['application_20was_20unable_20to_20start_20correctly_200xc000007b_28',['&quot;The application was unable to start correctly (0xc000007b)&quot;',['../md_docs_2getting__started_2installation.html#the-application-was-unable-to-start-correctly-0xc000007b',1,'']]],
  ['applications_29',['Other Applications',['../md_docs_2COMPUTE.html#other-applications',1,'']]],
  ['apply_5fradius_5fchange_30',['apply_radius_change',['../voxel__main_8c.html#a337fcbf862cb95d02e717c47a74cd869',1,'voxel_main.c']]],
  ['architectural_20differences_31',['Architectural Differences',['../md_docs_2manual_2voxel__rendering.html#architectural-differences',1,'']]],
  ['architecture_32',['Architecture',['../md_docs_2manual_2telemetry.html#architecture',1,'Architecture'],['../md_docs_2manual_2memory__management.html#block-header-architecture',1,'Block Header Architecture'],['../md_docs_2manual_2camera__system.html#camera-architecture',1,'Camera Architecture'],['../md_docs_2manual_2math__library.html',1,'Math Library Architecture'],['../md_docs_2manual_2memory__management.html',1,'Memory Management Architecture'],['../md_docs_2manual_2input__system.html',1,'SBgl Input System Architecture'],['../md_docs_2manual_2vulkan__backend.html',1,'SBgl Vulkan Backend Architecture'],['../md_docs_2manual_2voxel__rendering.html',1,'Voxel Rendering Architecture']]],
  ['architecture_20and_20design_33',['Architecture and Design',['../md_docs_2manual_2math__library.html#architecture-and-design',1,'']]],
  ['are_20reported_34',['When Errors Are Reported',['../md_docs_2manual_2windows__specific.html#when-errors-are-reported',1,'']]],
  ['area_20size_35',['Client Area Size',['../md_docs_2manual_2windows__specific.html#client-area-size',1,'']]],
  ['arena_36',['The Transient Arena',['../md_docs_2manual_2memory__management.html#the-transient-arena',1,'']]],
  ['arena_37',['arena',['../structsbgl__GfxContext.html#a4996512a8fd993d5cc776f1acd23b0b4',1,'sbgl_GfxContext::arena'],['../structsbgl__RenderQueue.html#af0d8742271c05ef716c5a5291bbd1215',1,'sbgl_RenderQueue::arena'],['../structsbgl__InternalContext.html#ad850e4314963cbecbf1913882ccaedef',1,'sbgl_InternalContext::arena']]],
  ['arena_20allocator_20sblarena_38',['The Arena Allocator (SblArena)',['../md_docs_2manual_2memory__management.html#the-arena-allocator-sblarena',1,'']]],
  ['arena_20hierarchy_20ascii_39',['Arena Hierarchy (ASCII)',['../md_docs_2manual_2memory__management.html#arena-hierarchy-ascii',1,'']]],
  ['ascii_40',['Arena Hierarchy (ASCII)',['../md_docs_2manual_2memory__management.html#arena-hierarchy-ascii',1,'']]],
  ['aspect_41',['aspect',['../structsbgl__Camera.html#a95d90d29f1d5d591bbab7777420e431d',1,'sbgl_Camera']]],
  ['attributecount_42',['attributeCount',['../structsbgl__VertexLayout.html#add8e0b16c2179a83b93a104d78fea448',1,'sbgl_VertexLayout']]],
  ['attributes_43',['attributes',['../structsbgl__VertexLayout.html#aa69ed279d85326a353914f2bd19f7d37',1,'sbgl_VertexLayout']]],
  ['automated_20batching_44',['Automated Batching',['../md_docs_2manual_2rendering__pipeline.html#automated-batching',1,'']]],
  ['awareness_45',['DPI Awareness',['../md_docs_2manual_2windows__specific.html#dpi-awareness',1,'']]]
];
