var searchData=
[
  ['h_20not_20found_0',['h not found',['../md_docs_2getting__started_2installation.html#wayland-clienth-not-found',1,'&quot;wayland-client.h not found&quot;'],['../md_docs_2getting__started_2installation.html#x11xlibh-not-found',1,'&quot;X11/Xlib.h not found&quot;']]],
  ['h_20tt_1',['The Interface (&lt;tt&gt;sbgl_platform.h&lt;/tt&gt;)',['../md_docs_2manual_2platform__abstraction.html#the-interface-sbgl_platformh',1,'']]],
  ['hal_2',['HAL',['../index.html#chapter-2-the-graphics-hal',1,'Chapter 2: The Graphics HAL'],['../md_docs_2manual_2platform__abstraction.html',1,'SBgl Platform Abstraction Layer (HAL)']]],
  ['hal_20context_20foundation_3',['HAL &amp; Context Foundation',['../md_docs_2ROADMAP.html#hal--context-foundation',1,'']]],
  ['hal_20implementation_4',['Input HAL Implementation',['../md_docs_2manual_2input__system.html#input-hal-implementation',1,'']]],
  ['hal_20interface_5',['Core HAL Interface',['../md_docs_2manual_2platform__abstraction.html#core-hal-interface',1,'']]],
  ['handle_6',['handle',['../structSBGL__VulkanBuffer.html#abe08a66bb8ccadf4323aed7f36862335',1,'SBGL_VulkanBuffer::handle'],['../structSBGL__VulkanPipeline.html#a55dc3b90a1c05973fbf90e9f6e04443a',1,'SBGL_VulkanPipeline::handle'],['../structSBGL__VulkanComputePipeline.html#a85a846f034afc8dfe401d6323a78f601',1,'SBGL_VulkanComputePipeline::handle']]],
  ['handle_20based_20resource_20management_7',['Handle-Based Resource Management',['../md_docs_2manual_2rendering__pipeline.html#handle-based-resource-management',1,'']]],
  ['handle_5findex_8',['handle_index',['../structsbgl__GfxMemoryRange.html#acf52dcbf70e83d7847d81372ea6ad117',1,'sbgl_GfxMemoryRange']]],
  ['handling_9',['Handling',['../md_docs_2ROADMAP.html#api-standardization--error-handling',1,'API Standardization &amp; Error Handling'],['../md_docs_2manual_2windows__specific.html#dpi-change-handling',1,'DPI Change Handling'],['../md_docs_2manual_2windows__specific.html#legacy-modifier-handling',1,'Legacy Modifier Handling']]],
  ['hardcoded_20static_20loading_10',['Hardcoded (Static) Loading',['../md_docs_2manual_2rendering__pipeline.html#hardcoded-static-loading',1,'']]],
  ['hasstartedframe_11',['hasStartedFrame',['../structsbgl__InternalContext.html#a67c99b01bda763ae80ba03a43bb20e30',1,'sbgl_InternalContext']]],
  ['head_12',['head',['../structSblArena.html#a7521b2329fa824fa309449deae27526b',1,'SblArena']]],
  ['header_13',['header',['../structsbgl__DrawPacket.html#aaa2f7ff5dcd79db37af23fa139f92aec',1,'sbgl_DrawPacket']]],
  ['header_20architecture_14',['Block Header Architecture',['../md_docs_2manual_2memory__management.html#block-header-architecture',1,'']]],
  ['heap_20range_20tracking_15',['Managed Heap Range Tracking',['../md_docs_2manual_2vulkan__backend.html#managed-heap-range-tracking',1,'']]],
  ['heaps_16',['The Three GPU Heaps',['../md_docs_2manual_2memory__management.html#the-three-gpu-heaps',1,'']]],
  ['heaptype_17',['heapType',['../structSBGL__VulkanBuffer.html#acf0fc0bc33bfb0b08c4e1e574282b901',1,'SBGL_VulkanBuffer']]],
  ['height_18',['height',['../structsbgl__Window.html#a45199e5dcb4b687a579314de9d227bec',1,'sbgl_Window']]],
  ['heightaddress_19',['heightAddress',['../structVoxelPushConstants.html#a4acecdabbe76b0ce732cca697ad2ed74',1,'VoxelPushConstants']]],
  ['hello_5fwindow_2ec_20',['hello_window.c',['../hello__window_8c.html',1,'']]],
  ['hidden_20mode_20tt_20sbgl_5fmouse_5fmode_5fhidden_20tt_21',['Hidden Mode (&lt;tt&gt;SBGL_MOUSE_MODE_HIDDEN&lt;/tt&gt;)',['../md_docs_2manual_2windows__specific.html#hidden-mode-sbgl_mouse_mode_hidden',1,'']]],
  ['hierarchy_20and_20ownership_22',['Core Hierarchy and Ownership',['../md_docs_2manual_2memory__management.html#core-hierarchy-and-ownership',1,'']]],
  ['hierarchy_20ascii_23',['Arena Hierarchy (ASCII)',['../md_docs_2manual_2memory__management.html#arena-hierarchy-ascii',1,'']]],
  ['high_20level_20rendering_20text_20sprites_24',['High-Level rendering (Text/Sprites)',['../md_docs_2ROADMAP.html#high-level-rendering-textsprites',1,'']]],
  ['hinstance_25',['hinstance',['../structsbgl__Window.html#aea7bd2cab889bb13a97506a56ab3b278',1,'sbgl_Window']]],
  ['hit_26',['hit',['../structsbgl__HitResult.html#ad5e8955a48e650c29cf5f7743aeed5bf',1,'sbgl_HitResult']]],
  ['hwnd_27',['hwnd',['../structsbgl__Window.html#a6e2409273f2ef5f51e0c8ae658dd19a5',1,'sbgl_Window']]],
  ['hybrid_20gpu_20memory_20management_28',['Hybrid GPU Memory Management',['../md_docs_2manual_2memory__management.html#hybrid-gpu-memory-management',1,'']]],
  ['hybrid_20gpu_20memory_20manager_29',['Hybrid GPU Memory Manager',['../md_docs_2manual_2vulkan__backend.html#hybrid-gpu-memory-manager',1,'']]]
];
