var searchData=
[
  ['table_20of_20contents_0',['Table of Contents',['../md_docs_2manual_2windows__specific.html#table-of-contents',1,'']]],
  ['target_1',['target',['../structsbgl__Camera.html#a54c5eceebad7014aa89a75f3ed970b46',1,'sbgl_Camera']]],
  ['teardown_2',['GPU Synchronization &amp; Teardown',['../md_docs_2manual_2vulkan__backend.html#gpu-synchronization--teardown',1,'']]],
  ['teardown_20pattern_3',['Safe Teardown Pattern',['../md_docs_2manual_2vulkan__backend.html#safe-teardown-pattern',1,'']]],
  ['technical_20detail_20brace_20initialization_4',['Technical Detail (Brace Initialization)',['../md_docs_2manual_2math__library.html#technical-detail-brace-initialization',1,'']]],
  ['technical_20summary_5',['Technical Summary',['../md_docs_2manual_2input__system.html#technical-summary',1,'Technical Summary'],['../md_docs_2manual_2memory__management.html#technical-summary-1',1,'Technical Summary'],['../md_docs_2manual_2vulkan__backend.html#technical-summary-2',1,'Technical Summary']]],
  ['techniques_6',['Techniques',['../index.html#chapter-4-advanced-techniques',1,'Chapter 4: Advanced Techniques'],['../md_README.html#performance--rendering-techniques',1,'Performance &amp; Rendering Techniques']]],
  ['telemetry_20structure_7',['The Telemetry Structure',['../md_docs_2manual_2telemetry.html#the-telemetry-structure',1,'']]],
  ['telemetry_20system_8',['Performance Telemetry System',['../md_docs_2manual_2telemetry.html',1,'']]],
  ['telemetry_2emd_9',['telemetry.md',['../telemetry_8md.html',1,'']]],
  ['telemetry_5ftimer_10',['telemetry_timer',['../structsbgl__VoxelSystem.html#ab81325e49c33a9465ff20145a6f5cc90',1,'sbgl_VoxelSystem']]],
  ['testing_11',['Intersection Testing',['../md_docs_2manual_2camera__system.html#intersection-testing',1,'']]],
  ['text_20sprites_12',['High-Level rendering (Text/Sprites)',['../md_docs_2ROADMAP.html#high-level-rendering-textsprites',1,'']]],
  ['textureid_13',['textureID',['../structsbgl__Material.html#acdac3ae950dbba70f37235c35f430aef',1,'sbgl_Material']]],
  ['the_20application_20was_20unable_20to_20start_20correctly_200xc000007b_14',['&quot;The application was unable to start correctly (0xc000007b)&quot;',['../md_docs_2getting__started_2installation.html#the-application-was-unable-to-start-correctly-0xc000007b',1,'']]],
  ['the_20arena_20allocator_20sblarena_15',['The Arena Allocator (SblArena)',['../md_docs_2manual_2memory__management.html#the-arena-allocator-sblarena',1,'']]],
  ['the_20code_20execution_20cannot_20proceed_20because_20vulkan_201_20dll_20was_20not_20found_16',['&quot;The code execution cannot proceed because vulkan-1.dll was not found&quot;',['../md_docs_2getting__started_2installation.html#the-code-execution-cannot-proceed-because-vulkan-1dll-was-not-found',1,'']]],
  ['the_20compute_20api_17',['Using the Compute API',['../md_docs_2COMPUTE.html#using-the-compute-api',1,'']]],
  ['the_20context_18',['Initializing the Context',['../md_docs_2getting__started_2window__setup.html#initializing-the-context',1,'']]],
  ['the_20data_20oriented_20pipeline_19',['Chapter 3: The Data-Oriented Pipeline',['../index.html#chapter-3-the-data-oriented-pipeline',1,'']]],
  ['the_20examples_20',['Building the Examples',['../md_docs_2examples_2index.html#building-the-examples',1,'']]],
  ['the_20graphics_20hal_21',['Chapter 2: The Graphics HAL',['../index.html#chapter-2-the-graphics-hal',1,'']]],
  ['the_20interface_20tt_20sbgl_5fplatform_20h_20tt_22',['The Interface (&lt;tt&gt;sbgl_platform.h&lt;/tt&gt;)',['../md_docs_2manual_2platform__abstraction.html#the-interface-sbgl_platformh',1,'']]],
  ['the_20key_20map_20pattern_23',['The Key Map Pattern',['../md_docs_2manual_2input__system.html#the-key-map-pattern',1,'']]],
  ['the_20main_20loop_24',['The Main Loop',['../md_docs_2getting__started_2window__setup.html#the-main-loop',1,'']]],
  ['the_20mouse_20mode_25',['Controlling the Mouse Mode',['../md_docs_2manual_2input__system.html#controlling-the-mouse-mode',1,'']]],
  ['the_20queue_26',['Executing the Queue',['../md_docs_2manual_2rendering__pipeline.html#executing-the-queue',1,'']]],
  ['the_20telemetry_20structure_27',['The Telemetry Structure',['../md_docs_2manual_2telemetry.html#the-telemetry-structure',1,'']]],
  ['the_20three_20gpu_20heaps_28',['The Three GPU Heaps',['../md_docs_2manual_2memory__management.html#the-three-gpu-heaps',1,'']]],
  ['the_20transient_20arena_29',['The Transient Arena',['../md_docs_2manual_2memory__management.html#the-transient-arena',1,'']]],
  ['thread_20local_20memory_30',['Thread-Local Memory',['../md_docs_2ROADMAP.html#thread-local-memory',1,'']]],
  ['threaded_20architecture_31',['Multi-Threaded Architecture',['../md_docs_2ROADMAP.html#multi-threaded-architecture',1,'']]],
  ['three_20gpu_20heaps_32',['The Three GPU Heaps',['../md_docs_2manual_2memory__management.html#the-three-gpu-heaps',1,'']]],
  ['tiling_20periodicity_33',['Seamless Tiling &amp; Periodicity',['../md_docs_2manual_2voxel__rendering.html#seamless-tiling--periodicity',1,'']]],
  ['time_34',['time',['../structPushData.html#a85623e3bbc2cb6ae1b429afc395feafb',1,'PushData']]],
  ['timestampperiod_35',['timestampPeriod',['../structsbgl__GfxContext.html#a46afee44ecd2418525dc0275e4711b77',1,'sbgl_GfxContext']]],
  ['timing_20precision_36',['Timing Precision',['../md_docs_2manual_2telemetry.html#timing-precision',1,'']]],
  ['to_20compile_37',['Examples build but shaders fail to compile',['../md_docs_2getting__started_2installation.html#examples-build-but-shaders-fail-to-compile',1,'']]],
  ['to_20start_20correctly_200xc000007b_38',['&quot;The application was unable to start correctly (0xc000007b)&quot;',['../md_docs_2getting__started_2installation.html#the-application-was-unable-to-start-correctly-0xc000007b',1,'']]],
  ['to_20transform_20mapping_39',['Input-to-Transform Mapping',['../md_docs_2manual_2input__system.html#input-to-transform-mapping',1,'']]],
  ['to_20windows_40',['Cross-Compilation (Linux to Windows)',['../md_docs_2getting__started_2installation.html#cross-compilation-linux-to-windows',1,'']]],
  ['top_41',['top',['../structsbgl__OrthoParams.html#a7314013ee90ead5475533f2d393f8d0b',1,'sbgl_OrthoParams']]],
  ['toplevel_5fhandle_5fclose_42',['toplevel_handle_close',['../window__wayland_8c.html#a579545bf952ffcb00563965cccfff85e',1,'window_wayland.c']]],
  ['toplevel_5fhandle_5fconfigure_43',['toplevel_handle_configure',['../window__wayland_8c.html#a3b45bd30e099e965313d8c520abb5d08',1,'window_wayland.c']]],
  ['toplevel_5flistener_44',['toplevel_listener',['../window__wayland_8c.html#a9223f308a55b463d9d3ce8ad18b361a9',1,'window_wayland.c']]],
  ['total_5fframes_45',['total_frames',['../structsbgl__VoxelSystem.html#af52cb7db096c8e756544261c614f68a6',1,'sbgl_VoxelSystem']]],
  ['tracking_46',['Managed Heap Range Tracking',['../md_docs_2manual_2vulkan__backend.html#managed-heap-range-tracking',1,'']]],
  ['traditional_20meshing_47',['Comparison: Procedural vs. Traditional Meshing',['../md_docs_2manual_2voxel__rendering.html#comparison-procedural-vs-traditional-meshing',1,'']]],
  ['transfer_48',['Ownership Transfer',['../md_docs_2manual_2memory__management.html#ownership-transfer',1,'']]],
  ['transform_49',['transform',['../structsbgl__InstanceData.html#a2a21f45b280fcaa94d9f0531d1794095',1,'sbgl_InstanceData']]],
  ['transform_20mapping_50',['Input-to-Transform Mapping',['../md_docs_2manual_2input__system.html#input-to-transform-mapping',1,'']]],
  ['transformation_20matrices_51',['Transformation Matrices',['../md_docs_2manual_2math__library.html#transformation-matrices',1,'']]],
  ['transformations_52',['Matrix Transformations',['../md_docs_2manual_2math__library.html#matrix-transformations',1,'']]],
  ['transient_20arena_53',['The Transient Arena',['../md_docs_2manual_2memory__management.html#the-transient-arena',1,'']]],
  ['transientarena_54',['transientArena',['../structsbgl__InternalContext.html#adf2dcd3d28f3a35e49ffae521e354bbf',1,'sbgl_InternalContext']]],
  ['transientbuffers_55',['transientBuffers',['../structsbgl__GfxContext.html#a379b5c65d9c5cdaf2b35d9f79c269b82',1,'sbgl_GfxContext']]],
  ['transientmapped_56',['transientMapped',['../structsbgl__GfxContext.html#a03d781e0a59691f219c37239f917a88d',1,'sbgl_GfxContext']]],
  ['transientoffsets_57',['transientOffsets',['../structsbgl__GfxContext.html#a29fb3f5149347853aed25402c16a9bc7',1,'sbgl_GfxContext']]],
  ['triangle_20rendering_58',['Vertex Buffers &amp; Triangle Rendering',['../md_docs_2ROADMAP.html#vertex-buffers--triangle-rendering',1,'']]],
  ['triangle_20rendering_20guide_59',['Triangle Rendering Guide',['../md_docs_2getting__started_2first__triangle.html',1,'']]],
  ['triangle_5fmain_2ec_60',['triangle_main.c',['../triangle__main_8c.html',1,'']]],
  ['triggers_61',['Platform-Specific Triggers',['../md_docs_2manual_2platform__abstraction.html#platform-specific-triggers',1,'']]],
  ['troubleshooting_62',['Troubleshooting',['../md_docs_2getting__started_2installation.html#troubleshooting',1,'']]],
  ['troubleshooting_20mingw_20builds_63',['Troubleshooting MinGW Builds',['../md_docs_2getting__started_2installation.html#troubleshooting-mingw-builds',1,'']]],
  ['tt_64',['tt',['../md_docs_2manual_2windows__specific.html#captured-mode-sbgl_mouse_mode_captured',1,'Captured Mode (&lt;tt&gt;SBGL_MOUSE_MODE_CAPTURED&lt;/tt&gt;)'],['../md_docs_2manual_2windows__specific.html#hidden-mode-sbgl_mouse_mode_hidden',1,'Hidden Mode (&lt;tt&gt;SBGL_MOUSE_MODE_HIDDEN&lt;/tt&gt;)'],['../md_docs_2manual_2windows__specific.html#normal-mode-sbgl_mouse_mode_normal',1,'Normal Mode (&lt;tt&gt;SBGL_MOUSE_MODE_NORMAL&lt;/tt&gt;)'],['../md_docs_2manual_2platform__abstraction.html#relationship-with-sbgl_context',1,'Relationship with &lt;tt&gt;sbgl_Context&lt;/tt&gt;'],['../md_docs_2manual_2platform__abstraction.html#the-interface-sbgl_platformh',1,'The Interface (&lt;tt&gt;sbgl_platform.h&lt;/tt&gt;)']]],
  ['tt_20sbgl_5fcontext_20tt_65',['Relationship with &lt;tt&gt;sbgl_Context&lt;/tt&gt;',['../md_docs_2manual_2platform__abstraction.html#relationship-with-sbgl_context',1,'']]],
  ['tt_20sbgl_5fmouse_5fmode_5fcaptured_20tt_66',['Captured Mode (&lt;tt&gt;SBGL_MOUSE_MODE_CAPTURED&lt;/tt&gt;)',['../md_docs_2manual_2windows__specific.html#captured-mode-sbgl_mouse_mode_captured',1,'']]],
  ['tt_20sbgl_5fmouse_5fmode_5fhidden_20tt_67',['Hidden Mode (&lt;tt&gt;SBGL_MOUSE_MODE_HIDDEN&lt;/tt&gt;)',['../md_docs_2manual_2windows__specific.html#hidden-mode-sbgl_mouse_mode_hidden',1,'']]],
  ['tt_20sbgl_5fmouse_5fmode_5fnormal_20tt_68',['Normal Mode (&lt;tt&gt;SBGL_MOUSE_MODE_NORMAL&lt;/tt&gt;)',['../md_docs_2manual_2windows__specific.html#normal-mode-sbgl_mouse_mode_normal',1,'']]],
  ['tt_20sbgl_5fplatform_20h_20tt_69',['The Interface (&lt;tt&gt;sbgl_platform.h&lt;/tt&gt;)',['../md_docs_2manual_2platform__abstraction.html#the-interface-sbgl_platformh',1,'']]],
  ['type_70',['type',['../structsbgl__Camera.html#a14d1ac6a5b188c2c3025d608f9d5384e',1,'sbgl_Camera::type'],['../structsbgl__ErrorDetail.html#a8c2c9144c965520ceac52f6bc37ee231',1,'sbgl_ErrorDetail::type']]],
  ['types_71',['Primary Data Types',['../md_docs_2manual_2math__library.html#primary-data-types',1,'']]]
];
