var searchData=
[
  ['backend_20architecture_0',['SBgl Vulkan Backend Architecture',['../md_docs_2manual_2vulkan__backend.html',1,'']]],
  ['backend_20multi_20context_20support_1',['Context-Based Backend (Multi-Context Support)',['../md_docs_2manual_2vulkan__backend.html#context-based-backend-multi-context-support',1,'']]],
  ['backend_20refactor_20multi_20context_20support_2',['Context-Based Backend Refactor (Multi-Context Support)',['../md_docs_2ROADMAP.html#context-based-backend-refactor-multi-context-support',1,'']]],
  ['based_20backend_20multi_20context_20support_3',['Context-Based Backend (Multi-Context Support)',['../md_docs_2manual_2vulkan__backend.html#context-based-backend-multi-context-support',1,'']]],
  ['based_20backend_20refactor_20multi_20context_20support_4',['Context-Based Backend Refactor (Multi-Context Support)',['../md_docs_2ROADMAP.html#context-based-backend-refactor-multi-context-support',1,'']]],
  ['based_20resource_20management_5',['Handle-Based Resource Management',['../md_docs_2manual_2rendering__pipeline.html#handle-based-resource-management',1,'']]],
  ['basic_20example_6',['Basic example',['../md_README.html#basic-example',1,'']]],
  ['basic_20example_20pattern_7',['Basic Example Pattern',['../md_docs_2examples_2index.html#basic-example-pattern',1,'']]],
  ['batch_20access_8',['Data-Oriented API (Batch Access)',['../md_docs_2manual_2input__system.html#data-oriented-api-batch-access',1,'']]],
  ['batch_20collision_9',['Camera System &amp; Batch Collision',['../md_docs_2ROADMAP.html#camera-system--batch-collision',1,'']]],
  ['batch_20collision_20math_10',['Batch Collision Math',['../md_docs_2manual_2camera__system.html#batch-collision-math',1,'']]],
  ['batch_20rendering_20dod_20alignment_11',['Batch Rendering &amp; DOD Alignment',['../md_docs_2manual_2rendering__pipeline.html#batch-rendering--dod-alignment',1,'']]],
  ['batch_20submission_12',['Optimized Batch Submission',['../md_docs_2manual_2rendering__pipeline.html#optimized-batch-submission',1,'']]],
  ['batch_5fmain_2ec_13',['batch_main.c',['../batch__main_8c.html',1,'']]],
  ['batching_14',['Automated Batching',['../md_docs_2manual_2rendering__pipeline.html#automated-batching',1,'']]],
  ['batching_20gpu_20optimization_15',['Batching &amp; GPU Optimization',['../md_docs_2examples_2index.html#batching--gpu-optimization',1,'']]],
  ['batching_20mdi_20bit_20packing_16',['GPU Optimization &amp; Batching (MDI/Bit-packing)',['../md_docs_2ROADMAP.html#gpu-optimization--batching-mdibit-packing',1,'']]],
  ['bda_17',['Buffer Device Address (BDA)',['../md_docs_2manual_2vulkan__backend.html#buffer-device-address-bda',1,'']]],
  ['because_20vulkan_201_20dll_20was_20not_20found_18',['&quot;The code execution cannot proceed because vulkan-1.dll was not found&quot;',['../md_docs_2getting__started_2installation.html#the-code-execution-cannot-proceed-because-vulkan-1dll-was-not-found',1,'']]],
  ['behavior_19',['Behavior',['../md_docs_2manual_2windows__specific.html#behavior',1,'Behavior'],['../md_docs_2manual_2windows__specific.html#key-repeat-behavior',1,'Key Repeat Behavior']]],
  ['behaviors_20',['Behaviors',['../md_docs_2manual_2windows__specific.html#summary-of-windows-specific-behaviors',1,'Summary of Windows-Specific Behaviors'],['../md_docs_2manual_2windows__specific.html',1,'Windows-Specific Features and Behaviors']]],
  ['benefits_21',['Data-Oriented Design (DOD) Benefits',['../md_docs_2manual_2memory__management.html#data-oriented-design-dod-benefits',1,'']]],
  ['between_20compute_20and_20graphics_20shaders_22',['Differences Between Compute and Graphics Shaders',['../md_docs_2COMPUTE.html#differences-between-compute-and-graphics-shaders',1,'']]],
  ['bit_20packing_23',['GPU Optimization &amp; Batching (MDI/Bit-packing)',['../md_docs_2ROADMAP.html#gpu-optimization--batching-mdibit-packing',1,'']]],
  ['blendmode_24',['blendMode',['../structsbgl__PipelineConfig.html#a67a060f298aa7fad139954af456dddcb',1,'sbgl_PipelineConfig']]],
  ['block_25',['block',['../structSblArenaMark.html#a29956797d83a5fa702da2c47424f1120',1,'SblArenaMark']]],
  ['block_20header_20architecture_26',['Block Header Architecture',['../md_docs_2manual_2memory__management.html#block-header-architecture',1,'']]],
  ['block_20layout_27',['Memory Block Layout',['../md_docs_2manual_2memory__management.html#memory-block-layout',1,'']]],
  ['bottleneck_20identification_28',['Bottleneck Identification',['../md_docs_2manual_2telemetry.html#bottleneck-identification',1,'']]],
  ['bottom_29',['bottom',['../structsbgl__OrthoParams.html#a25ae9a8fae73548c7569390f0aaa4614',1,'sbgl_OrthoParams']]],
  ['boundcomputepipeline_30',['boundComputePipeline',['../structsbgl__GfxContext.html#aeca44381965753f5db4403ba1b57fd54',1,'sbgl_GfxContext']]],
  ['boundpipeline_31',['boundPipeline',['../structsbgl__GfxContext.html#ad3439cabe68f47a670cfae9d9942b29b',1,'sbgl_GfxContext']]],
  ['brace_20initialization_32',['Technical Detail (Brace Initialization)',['../md_docs_2manual_2math__library.html#technical-detail-brace-initialization',1,'']]],
  ['buffer_33',['Vertex Buffer',['../md_docs_2getting__started_2first__triangle.html#vertex-buffer',1,'']]],
  ['buffer_34',['buffer',['../structsbgl__GfxTransientAllocation.html#a83bb0f558818a483f04b6226b1d4b9f7',1,'sbgl_GfxTransientAllocation']]],
  ['buffer_20device_20address_20bda_35',['Buffer Device Address (BDA)',['../md_docs_2manual_2vulkan__backend.html#buffer-device-address-bda',1,'']]],
  ['bufferactive_36',['bufferActive',['../structsbgl__GfxContext.html#aec06808c382ccdd9cabde15c90d503dd',1,'sbgl_GfxContext']]],
  ['buffering_203d_20sorting_37',['Depth Buffering &amp; 3D Sorting',['../md_docs_2manual_2rendering__pipeline.html#depth-buffering--3d-sorting',1,'']]],
  ['buffers_38',['buffers',['../structsbgl__GfxContext.html#aaf0d62e9a21ec497610c718793e4279e',1,'sbgl_GfxContext']]],
  ['buffers_20triangle_20rendering_39',['Vertex Buffers &amp; Triangle Rendering',['../md_docs_2ROADMAP.html#vertex-buffers--triangle-rendering',1,'']]],
  ['build_20but_20shaders_20fail_20to_20compile_40',['Examples build but shaders fail to compile',['../md_docs_2getting__started_2installation.html#examples-build-but-shaders-fail-to-compile',1,'']]],
  ['build_20instructions_41',['Build Instructions',['../md_docs_2getting__started_2installation.html#build-instructions',1,'Build Instructions'],['../md_docs_2getting__started_2installation.html#build-instructions-1',1,'Build Instructions']]],
  ['building_20from_20developer_20command_20prompt_42',['Building from Developer Command Prompt',['../md_docs_2getting__started_2installation.html#building-from-developer-command-prompt',1,'']]],
  ['building_20from_20scratch_43',['Building from scratch',['../md_README.html#building-from-scratch',1,'']]],
  ['building_20from_20visual_20studio_20ide_44',['Building from Visual Studio IDE',['../md_docs_2getting__started_2installation.html#building-from-visual-studio-ide',1,'']]],
  ['building_20the_20examples_45',['Building the Examples',['../md_docs_2examples_2index.html#building-the-examples',1,'']]],
  ['builds_46',['Troubleshooting MinGW Builds',['../md_docs_2getting__started_2installation.html#troubleshooting-mingw-builds',1,'']]],
  ['but_20shaders_20fail_20to_20compile_47',['Examples build but shaders fail to compile',['../md_docs_2getting__started_2installation.html#examples-build-but-shaders-fail-to-compile',1,'']]]
];
