var searchData=
[
  ['data_20initialization_0',['Data Initialization',['../md_docs_2manual_2math__library.html#data-initialization',1,'']]],
  ['data_20oriented_20api_20batch_20access_1',['Data-Oriented API (Batch Access)',['../md_docs_2manual_2input__system.html#data-oriented-api-batch-access',1,'']]],
  ['data_20oriented_20design_20dod_20benefits_2',['Data-Oriented Design (DOD) Benefits',['../md_docs_2manual_2memory__management.html#data-oriented-design-dod-benefits',1,'']]],
  ['data_20oriented_20metadata_20passthrough_3',['Data-Oriented Metadata Passthrough',['../md_docs_2manual_2voxel__rendering.html#data-oriented-metadata-passthrough',1,'']]],
  ['data_20oriented_20pipeline_4',['Chapter 3: The Data-Oriented Pipeline',['../index.html#chapter-3-the-data-oriented-pipeline',1,'']]],
  ['data_20types_5',['Primary Data Types',['../md_docs_2manual_2math__library.html#primary-data-types',1,'']]],
  ['debugging_20validation_6',['Debugging &amp; Validation',['../md_docs_2manual_2vulkan__backend.html#debugging--validation',1,'']]],
  ['default_7',['Console Subsystem (Default)',['../md_docs_2manual_2windows__specific.html#console-subsystem-default',1,'']]],
  ['deferredbuffers_8',['deferredBuffers',['../structsbgl__GfxContext.html#a1301afafa636e6cce7b38a486ca6a296',1,'sbgl_GfxContext']]],
  ['deferredcount_9',['deferredCount',['../structsbgl__GfxContext.html#a8eb52e64f741ca7eebd2b7f112687f3c',1,'sbgl_GfxContext']]],
  ['deltas_10',['Mouse Deltas',['../md_docs_2manual_2input__system.html#mouse-deltas',1,'']]],
  ['dependencies_11',['Dependencies',['../md_README.html#dependencies',1,'Dependencies'],['../md_docs_2getting__started_2installation.html#system-dependencies',1,'System Dependencies']]],
  ['dependency_20management_12',['Dependency Management',['../md_docs_2getting__started_2installation.html#dependency-management',1,'']]],
  ['depth_20buffering_203d_20sorting_13',['Depth Buffering &amp; 3D Sorting',['../md_docs_2manual_2rendering__pipeline.html#depth-buffering--3d-sorting',1,'']]],
  ['depthformat_14',['depthFormat',['../structsbgl__GfxContext.html#ae21b6b54026296317728f36ba3e38460',1,'sbgl_GfxContext']]],
  ['depthimage_15',['depthImage',['../structsbgl__GfxContext.html#aa74a7a41f168bbc56b16cc7ae54e9755',1,'sbgl_GfxContext']]],
  ['depthimageview_16',['depthImageView',['../structsbgl__GfxContext.html#ae74a176fdf7d88358f8b8d5c04e31496',1,'sbgl_GfxContext']]],
  ['depthmemory_17',['depthMemory',['../structsbgl__GfxContext.html#ac1703d39daa3f3c6da15bae97de8a747',1,'sbgl_GfxContext']]],
  ['design_18',['Architecture and Design',['../md_docs_2manual_2math__library.html#architecture-and-design',1,'']]],
  ['design_20dod_20benefits_19',['Data-Oriented Design (DOD) Benefits',['../md_docs_2manual_2memory__management.html#data-oriented-design-dod-benefits',1,'']]],
  ['detail_20brace_20initialization_20',['Technical Detail (Brace Initialization)',['../md_docs_2manual_2math__library.html#technical-detail-brace-initialization',1,'']]],
  ['developer_20command_20prompt_21',['Building from Developer Command Prompt',['../md_docs_2getting__started_2installation.html#building-from-developer-command-prompt',1,'']]],
  ['development_20notes_22',['Internal Development Notes',['../md_README.html#internal-development-notes',1,'']]],
  ['device_23',['device',['../structsbgl__GfxContext.html#acb292fd1a972d7755d1b4dcdde609357',1,'sbgl_GfxContext']]],
  ['device_20address_20bda_24',['Buffer Device Address (BDA)',['../md_docs_2manual_2vulkan__backend.html#buffer-device-address-bda',1,'']]],
  ['device_20and_20queue_20management_25',['Logical Device and Queue Management',['../md_docs_2manual_2vulkan__backend.html#logical-device-and-queue-management',1,'']]],
  ['device_20selection_26',['Physical Device Selection',['../md_docs_2manual_2vulkan__backend.html#physical-device-selection',1,'']]],
  ['deviceaddress_27',['deviceAddress',['../structsbgl__GfxTransientAllocation.html#aa44ba87f3f48b8ceadb302ae68b9479a',1,'sbgl_GfxTransientAllocation']]],
  ['differences_28',['Architectural Differences',['../md_docs_2manual_2voxel__rendering.html#architectural-differences',1,'']]],
  ['differences_20between_20compute_20and_20graphics_20shaders_29',['Differences Between Compute and Graphics Shaders',['../md_docs_2COMPUTE.html#differences-between-compute-and-graphics-shaders',1,'']]],
  ['direction_30',['direction',['../structsbgl__Ray.html#a508a4be4e5473ff2522b1070deaebfec',1,'sbgl_Ray']]],
  ['dispatching_20work_31',['Dispatching Work',['../md_docs_2COMPUTE.html#dispatching-work',1,'']]],
  ['display_32',['display',['../structsbgl__Window.html#aaf770def8cd665bec769d46d869e7e57',1,'sbgl_Window']]],
  ['distance_33',['distance',['../structsbgl__HitResult.html#aaa2c40cf0a08a2c35baa27638f2af3e9',1,'sbgl_HitResult']]],
  ['distance_20control_34',['Render Distance Control',['../md_docs_2manual_2voxel__rendering.html#render-distance-control',1,'']]],
  ['dll_20was_20not_20found_35',['&quot;The code execution cannot proceed because vulkan-1.dll was not found&quot;',['../md_docs_2getting__started_2installation.html#the-code-execution-cannot-proceed-because-vulkan-1dll-was-not-found',1,'']]],
  ['documentation_36',['Documentation',['../md_README.html#documentation',1,'']]],
  ['documentation_20index_37',['SBgl Documentation Index',['../index.html',1,'']]],
  ['dod_20alignment_38',['Batch Rendering &amp; DOD Alignment',['../md_docs_2manual_2rendering__pipeline.html#batch-rendering--dod-alignment',1,'']]],
  ['dod_20benefits_39',['Data-Oriented Design (DOD) Benefits',['../md_docs_2manual_2memory__management.html#data-oriented-design-dod-benefits',1,'']]],
  ['dpi_20awareness_40',['DPI Awareness',['../md_docs_2manual_2windows__specific.html#dpi-awareness',1,'']]],
  ['dpi_20change_20handling_41',['DPI Change Handling',['../md_docs_2manual_2windows__specific.html#dpi-change-handling',1,'']]],
  ['draw_20indirect_20mdi_42',['Multi-Draw Indirect (MDI)',['../md_docs_2manual_2rendering__pipeline.html#multi-draw-indirect-mdi',1,'']]],
  ['draw_5fcalls_43',['draw_calls',['../structsbgl__Telemetry.html#a5ae42b7ae0508f4a3ff8576518e82947',1,'sbgl_Telemetry']]],
  ['drawing_44',['Drawing',['../md_docs_2getting__started_2first__triangle.html#drawing',1,'Drawing'],['../md_docs_2manual_2vulkan__backend.html#indirect-drawing',1,'Indirect Drawing']]],
  ['drawing_20example_45',['Complete Drawing Example',['../md_docs_2manual_2rendering__pipeline.html#complete-drawing-example',1,'']]],
  ['draws_46',['Submitting Draws',['../md_docs_2manual_2rendering__pipeline.html#submitting-draws',1,'']]],
  ['driven_20frustum_20culling_47',['GPU-Driven Frustum Culling',['../md_docs_2COMPUTE.html#gpu-driven-frustum-culling',1,'']]],
  ['driven_20pipeline_48',['GPU-Driven Pipeline',['../md_docs_2manual_2voxel__rendering.html#gpu-driven-pipeline',1,'']]],
  ['dynamic_20clearing_49',['Dynamic Clearing',['../md_docs_2manual_2vulkan__backend.html#dynamic-clearing',1,'']]],
  ['dynamic_20file_20loading_50',['Dynamic File Loading',['../md_docs_2manual_2rendering__pipeline.html#dynamic-file-loading',1,'']]],
  ['dynamic_20resource_20management_20mark_20rewind_51',['Dynamic Resource Management (Mark/Rewind)',['../md_docs_2manual_2memory__management.html#dynamic-resource-management-markrewind',1,'']]],
  ['dynamic_20swapchain_20recreation_20mark_20rewind_52',['Dynamic Swapchain Recreation (Mark/Rewind)',['../md_docs_2manual_2vulkan__backend.html#dynamic-swapchain-recreation-markrewind',1,'']]],
  ['dynamic_20vertex_20updates_53',['Dynamic Vertex Updates',['../md_docs_2manual_2rendering__pipeline.html#dynamic-vertex-updates',1,'']]],
  ['dynamic_5fheap_5falloc_54',['dynamic_heap_alloc',['../sbgl__backend__vulkan_8c.html#ad00e94b8e3dd098b5fe954ce9bff715f',1,'sbgl_backend_vulkan.c']]],
  ['dynamicheap_55',['dynamicHeap',['../structsbgl__GfxContext.html#a170079f75fc3e346959d41bbfeb5f2bb',1,'sbgl_GfxContext']]]
];
